services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: issueflow-sql
    environment:
      SA_PASSWORD: "YourStrong!Pass123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  api:
    build:
      context: ./IssueFlowApi
      dockerfile: Dockerfile
    container_name: issueflow-api
    ports:
      - "5176:8080"
    depends_on:
      - sqlserver
    environment:
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=IssueFlowDb;User Id=sa;Password=YourStrong!Pass123;TrustServerCertificate=True"

volumes:
  sql_data: